---
- name: NGINX
  hosts: default
  become: true
  vars:
    nginx_listen_port: 8080

  tasks:
    - name: update
      apt:
        update_cache=yes
      tags:
        - update apt
    
    - name: NGINX install
      apt:
        name: nginx
        state: latest
      tags:
        - nginx-package

    - name: NGINX create config
      template:
        src: templates/nginx.conf.j2
        dest: /tmp/nginx.conf
      tags:
        - nginx-configuration

  handlers:
    - name: restart nginx
      systemd:
        name: nginx 
        state: restarted
        enabled: yes
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded
        enabled: yes 